export const questionsByCategory: Record<string, string[]> = {
  Technology: [
    "Tell me about yourself and your experience in software development.",
    "Walk me through a complex technical problem you solved recently.",
    "How do you approach system design for scalable applications?",
    "Describe your experience with our tech stack.",
    "What's your process for code review and ensuring code quality?",
    "How do you stay updated with new technologies and frameworks?",
    "Tell me about a time you had to debug a critical production issue.",
    "How do you handle technical debt in your projects?",
    "Describe your experience with microservices architecture.",
    "What's your approach to writing unit tests and achieving good test coverage?",
    "How do you optimize application performance?",
    "Tell me about a disagreement you had with a team member about a technical decision.",
    "What's your experience with CI/CD pipelines?",
    "How do you ensure security best practices in your code?",
    "Describe a time you had to learn a new technology quickly.",
    "What's your approach to documentation?",
    "How do you balance technical excellence with meeting deadlines?",
    "Tell me about a project where you improved existing code or infrastructure.",
    "What metrics do you use to measure code quality?",
    "How do you mentor junior developers?",
    "Describe your experience working in an agile environment.",
    "What's your approach to handling legacy code?",
    "How do you prioritize technical improvements versus new features?",
    "Tell me about a time you made a significant architectural decision.",
    "What's your experience with cloud platforms like AWS, Azure, or GCP?",
    "How do you approach database schema design and optimization?",
    "Describe a time when you had to scale a system to handle increased load.",
    "What's your experience with containerization and orchestration tools like Docker and Kubernetes?",
    "How do you implement monitoring and observability in your applications?",
    "Tell me about a time you had to make a trade-off between perfect code and shipping on time.",
    "What's your approach to API design and versioning?",
    "How do you handle backward compatibility when making breaking changes?",
    "Describe your experience with event-driven architectures.",
    "What's your process for conducting technical interviews?",
    "How do you approach refactoring a large codebase?",
    "Tell me about a time you identified and fixed a performance bottleneck.",
    "What's your experience with serverless architectures?",
    "How do you ensure high availability and disaster recovery?",
    "Describe a time you had to deal with a major outage.",
    "What's your approach to testing strategies beyond unit tests?",
    "How do you handle dependencies and package management?",
    "Tell me about your experience with infrastructure as code.",
    "What's your approach to designing fault-tolerant systems?",
    "How do you handle data migration in production systems?",
    "Describe your experience with GraphQL or other API paradigms.",
    "What's your process for estimating technical work?",
    "How do you approach technical documentation for complex systems?",
    "Tell me about a time you improved developer productivity or experience.",
    "What's your experience with real-time systems or WebSockets?",
    "How do you approach caching strategies in distributed systems?"
  ],

  "Data Science": [
    "Tell me about yourself and your background in data science.",
    "Walk me through a machine learning project from start to finish.",
    "How do you approach feature engineering?",
    "What's your experience with different ML algorithms and when to use each?",
    "Describe a time when your model didn't perform well. How did you improve it?",
    "How do you handle imbalanced datasets?",
    "What's your process for validating model performance?",
    "Tell me about your experience with A/B testing.",
    "How do you explain complex statistical concepts to non-technical stakeholders?",
    "What's your approach to data cleaning and preprocessing?",
    "Describe your experience with big data technologies.",
    "How do you prevent overfitting in your models?",
    "What evaluation metrics do you use and why?",
    "Tell me about a time you had to work with messy or incomplete data.",
    "How do you approach exploratory data analysis?",
    "What's your experience with deep learning frameworks?",
    "How do you ensure your models are production-ready?",
    "Describe a time you used data to drive a business decision.",
    "What's your experience with time series analysis?",
    "How do you handle missing data?",
    "Tell me about your experience with data visualization tools.",
    "What's your approach to model deployment and monitoring?",
    "How do you stay current with new ML techniques and research?",
    "Describe a challenging data problem you solved.",
    "What's your experience with SQL and database querying?",
    "Tell me about a time you had to explain model bias or fairness concerns to stakeholders.",
    "How do you approach hyperparameter tuning for complex models?",
    "Describe your experience with natural language processing (NLP) and transformer models.",
    "What's your approach to building recommendation systems?",
    "How do you handle data drift in production ML models?",
    "Tell me about a time you had to debug a model that was underperforming in production.",
    "What's your experience with reinforcement learning applications?",
    "How do you approach causal inference and experimentation design?",
    "Describe a situation where you had to choose between model interpretability and accuracy.",
    "What's your experience with MLOps and model versioning?",
    "How do you handle ethical considerations in AI and machine learning?",
    "Tell me about your experience with computer vision and image recognition models.",
    "What's your approach to dealing with high-dimensional data?",
    "How do you validate that your model generalizes well to new data?",
    "Describe your experience with ensemble methods and when to use them.",
    "What's your approach to building real-time prediction systems?",
    "How do you handle class imbalance in classification problems?",
    "Tell me about a time you collaborated with software engineers to deploy a model.",
    "What's your experience with graph neural networks or graph-based models?",
    "How do you approach feature selection and dimensionality reduction?",
    "Describe a time you had to work with limited labeled data.",
    "What's your experience with distributed computing frameworks like Spark or Dask?",
    "How do you monitor and detect model degradation over time?",
    "Tell me about your approach to building embeddings for recommendation or search systems.",
    "What's your experience with Bayesian methods and probabilistic programming?"
  ],

  Product: [
    "Tell me about yourself and your product management experience.",
    "How do you prioritize features in a product roadmap?",
    "Walk me through how you would launch a new product.",
    "Describe a time when you had to say no to a feature request.",
    "How do you gather and incorporate user feedback?",
    "What frameworks do you use for product prioritization?",
    "Tell me about a product you managed from conception to launch.",
    "How do you work with engineering teams to define requirements?",
    "What metrics do you track to measure product success?",
    "Describe a time when a product launch didn't go as planned.",
    "How do you balance user needs with business goals?",
    "What's your approach to competitive analysis?",
    "Tell me about a time you had to pivot a product strategy.",
    "How do you conduct user research?",
    "What's your experience with A/B testing and experimentation?",
    "Describe how you would improve one of our products.",
    "How do you create and communicate product vision?",
    "Tell me about a time you disagreed with stakeholders about product direction.",
    "What's your process for writing product requirements documents?",
    "How do you manage multiple stakeholders with conflicting priorities?",
    "Describe your experience with agile product development.",
    "What's your approach to technical debt as a PM?",
    "How do you measure product-market fit?",
    "Tell me about a data-driven decision you made as a PM.",
    "What's your experience with go-to-market strategy?",
    "How do you define and track North Star metrics for your product?",
    "Tell me about a time you killed a feature or product. What was your reasoning?",
    "What's your approach to building a 0-to-1 product versus scaling an existing one?",
    "How do you balance building for current users versus acquiring new users?",
    "Describe your experience working with designers to create user-centric solutions.",
    "What's your process for conducting competitive teardowns?",
    "How do you approach pricing and monetization strategy?",
    "Tell me about a time you used qualitative and quantitative data together.",
    "What's your experience with platform or marketplace products?",
    "How do you handle scope creep during product development?",
    "Describe a time you had to make a product decision with incomplete information.",
    "What's your approach to building API products or developer tools?",
    "How do you ensure accessibility and inclusivity in product design?",
    "Tell me about your experience with mobile product development.",
    "What's your process for running effective product discovery?",
    "How do you build buy-in for a product vision across the organization?",
    "Describe a time you had to sunset or deprecate a product feature.",
    "What's your approach to managing product backlogs?",
    "How do you think about network effects in product design?",
    "Tell me about a time you collaborated with data science or ML teams.",
    "What's your experience with subscription or SaaS business models?",
    "How do you approach internationalization and localization?",
    "Describe your process for stakeholder communication and alignment.",
    "What's your approach to building for enterprise versus consumer users?",
    "How do you use customer journey mapping in your work?"
  ],

  Design: [
    "Tell me about yourself and your design background.",
    "Walk me through your design process from research to final delivery.",
    "How do you approach user research?",
    "Describe a challenging design problem you solved.",
    "How do you handle feedback and criticism of your designs?",
    "What's your experience with design systems?",
    "Tell me about a time you had to advocate for the user.",
    "How do you balance aesthetics with usability?",
    "What's your process for creating wireframes and prototypes?",
    "Describe a time when you had to design under tight constraints.",
    "How do you measure the success of your designs?",
    "What tools do you use and why?",
    "Tell me about a time you collaborated with developers on implementation.",
    "How do you stay updated with design trends?",
    "What's your approach to accessibility in design?",
    "Describe a project where you improved an existing user experience.",
    "How do you conduct usability testing?",
    "Tell me about a time you had to compromise on a design.",
    "What's your experience with mobile vs web design?",
    "How do you present and justify your design decisions?",
    "Describe your experience with design thinking methodologies.",
    "What's your approach to creating personas and user journeys?",
    "How do you handle conflicting feedback from stakeholders?",
    "Tell me about a design that you're particularly proud of.",
    "What's your process for iterating on designs based on data?",
    "How do you approach designing for different platforms and devices?",
    "Tell me about a time you had to design for accessibility compliance (WCAG 2.1).",
    "What's your experience with design tokens and component libraries?",
    "How do you conduct competitive UX analysis?",
    "Describe a time you used analytics data to inform design decisions.",
    "What's your approach to information architecture?",
    "How do you collaborate with product managers on feature prioritization?",
    "Tell me about your experience with motion design and micro-interactions.",
    "What's your process for conducting heuristic evaluations?",
    "How do you approach designing empty states and error messages?",
    "Describe a time you had to redesign a core user flow.",
    "What's your experience with design QA and handoff to developers?",
    "How do you ensure design consistency across different product surfaces?",
    "Tell me about a time you designed for internationalization.",
    "What's your approach to responsive and adaptive design?",
    "How do you balance business metrics with user experience quality?",
    "Describe your experience with user testing moderation and synthesis.",
    "What's your process for creating and maintaining design documentation?",
    "How do you approach dark mode or theme design?",
    "Tell me about a time you mentored other designers or facilitated design critiques.",
    "What's your experience with Figma, Sketch, or other design tools?",
    "How do you approach onboarding flows and first-time user experiences?",
    "Describe a time you had to sell a design concept to skeptical stakeholders.",
    "What's your approach to designing for data visualization?",
    "How do you incorporate inclusivity and diversity in your design work?"
  ],

  Marketing: [
    "Tell me about yourself and your marketing experience.",
    "How do you develop a marketing strategy for a new product?",
    "What metrics do you use to measure campaign success?",
    "Describe a successful marketing campaign you led.",
    "How do you identify and reach your target audience?",
    "What's your experience with digital marketing channels?",
    "Tell me about a campaign that didn't perform well and what you learned.",
    "How do you allocate marketing budget across channels?",
    "What's your approach to content marketing?",
    "Describe your experience with marketing automation tools.",
    "How do you work with sales teams to generate qualified leads?",
    "What's your process for conducting market research?",
    "Tell me about your experience with SEO and SEM.",
    "How do you measure ROI on marketing spend?",
    "What's your approach to building brand awareness?",
    "Describe a time you had to pivot a marketing strategy.",
    "How do you use data to inform marketing decisions?",
    "What's your experience with social media marketing?",
    "Tell me about a time you successfully increased customer acquisition.",
    "How do you create customer personas?",
    "What's your approach to email marketing?",
    "Describe your experience with influencer or partnership marketing.",
    "How do you stay updated with marketing trends?",
    "What's your experience with analytics tools like Google Analytics?",
    "Tell me about a time you had to work with a limited budget.",
    "How do you approach performance marketing and paid acquisition?",
    "What's your experience with account-based marketing (ABM)?",
    "Tell me about a time you optimized conversion rates across the funnel.",
    "How do you approach brand positioning and messaging?",
    "Describe your experience with marketing attribution modeling.",
    "What's your process for developing customer lifecycle marketing?",
    "How do you leverage user-generated content in campaigns?",
    "Tell me about a time you launched a product in a new market.",
    "What's your experience with growth marketing and experimentation?",
    "How do you approach customer retention and reducing churn?",
    "Describe your experience with video marketing and creative production.",
    "What's your approach to community building and engagement?",
    "How do you integrate AI and automation in your marketing strategies?",
    "Tell me about a time you managed a rebrand or brand refresh.",
    "What's your experience with podcast advertising or audio marketing?",
    "How do you approach marketing for mobile apps and app store optimization?",
    "Describe your process for competitive positioning and differentiation.",
    "What's your experience with marketing analytics and data visualization?",
    "How do you approach personalization at scale?",
    "Tell me about a time you built a referral or viral loop into a campaign.",
    "What's your experience with TikTok, Instagram Reels, or short-form video?",
    "How do you measure and improve customer lifetime value (LTV)?",
    "Describe your approach to crisis communications or reputation management.",
    "What's your experience with event marketing and experiential campaigns?",
    "How do you approach testing and optimization in digital campaigns?"
  ],

  Sales: [
    "Tell me about yourself and your sales experience.",
    "Walk me through your sales process from prospecting to close.",
    "How do you handle objections during a sales call?",
    "Describe your biggest sale and how you closed it.",
    "What's your approach to building rapport with prospects?",
    "How do you research prospects before reaching out?",
    "Tell me about a time you lost a deal. What did you learn?",
    "What metrics do you track to measure your sales performance?",
    "How do you manage your sales pipeline?",
    "Describe a time you exceeded your quota. How did you do it?",
    "What's your experience with CRM tools?",
    "How do you stay motivated during slow periods?",
    "Tell me about a complex B2B sale you navigated.",
    "What's your approach to cold calling or cold emailing?",
    "How do you handle pricing negotiations?",
    "Describe your experience with consultative selling.",
    "What's your strategy for upselling or cross-selling?",
    "How do you qualify leads effectively?",
    "Tell me about a time you turned a rejection into a sale.",
    "What's your approach to following up with prospects?",
    "How do you collaborate with marketing to generate leads?",
    "Describe a time you helped a customer solve a problem.",
    "What's your experience selling our type of product or service?",
    "How do you build long-term relationships with clients?",
    "Tell me about your most challenging sales negotiation.",
    "How do you approach multi-threaded enterprise sales?",
    "What's your experience with MEDDIC, BANT, or other qualification frameworks?",
    "Tell me about a time you closed a deal that was stuck in procurement.",
    "How do you handle competitive situations where you're not the lowest price?",
    "Describe your approach to account-based selling.",
    "What's your strategy for building a champion within a prospect organization?",
    "How do you navigate deals with multiple decision-makers?",
    "Tell me about a time you successfully expanded an existing account.",
    "What's your experience with value-based selling?",
    "How do you approach forecasting and pipeline management?",
    "Describe a time you had to walk away from a deal.",
    "What's your strategy for handling long sales cycles?",
    "How do you leverage social selling and LinkedIn in your process?",
    "Tell me about a time you created a custom demo or proof of concept.",
    "What's your approach to contract negotiations and legal reviews?",
    "How do you handle buyer ghosting or radio silence?",
    "Describe your experience selling to the C-suite.",
    "What's your process for creating mutual action plans with prospects?",
    "How do you approach renewals and preventing churn?",
    "Tell me about a time you successfully came back from missing quota.",
    "What's your experience with sales enablement tools and automation?",
    "How do you approach territory planning and account prioritization?",
    "Describe a time you mentored or coached other sales reps.",
    "What's your strategy for getting past gatekeepers?",
    "How do you handle procurement and vendor evaluations?"
  ],

  Finance: [
    "Tell me about yourself and your finance background.",
    "Walk me through a financial model you've built.",
    "How do you approach financial analysis and forecasting?",
    "Describe a time you identified a significant cost-saving opportunity.",
    "What's your experience with financial statements analysis?",
    "How do you evaluate investment opportunities?",
    "Tell me about a complex financial problem you solved.",
    "What metrics do you focus on when analyzing a company's performance?",
    "Describe your experience with budgeting and variance analysis.",
    "How do you stay updated with financial markets and regulations?",
    "What's your approach to risk assessment?",
    "Tell me about a time you presented financial findings to non-finance stakeholders.",
    "How do you ensure accuracy in your financial analysis?",
    "What's your experience with financial modeling tools?",
    "Describe a time you had to work under a tight deadline.",
    "How do you approach due diligence for M&A transactions?",
    "What's your understanding of valuation methodologies?",
    "Tell me about your experience with Excel and financial software.",
    "How do you handle conflicting priorities?",
    "What's your approach to scenario analysis?",
    "Describe a time you disagreed with a financial decision.",
    "How do you evaluate financial risks?",
    "What's your experience with regulatory compliance?",
    "Tell me about a project where your analysis drove key decisions.",
    "How do you approach cash flow analysis?",
    "What's your experience with DCF modeling and terminal value calculations?",
    "How do you approach working capital management?",
    "Tell me about a time you built a three-statement model from scratch.",
    "What's your experience with LBO modeling and private equity analysis?",
    "How do you assess the quality of earnings in a company?",
    "Describe your approach to financial planning and analysis (FP&A).",
    "What's your experience with treasury operations and cash management?",
    "How do you evaluate debt financing versus equity financing options?",
    "Tell me about a time you identified accounting irregularities or red flags.",
    "What's your approach to building investor presentations and pitch decks?",
    "How do you analyze unit economics and contribution margins?",
    "Describe your experience with SaaS metrics like ARR, MRR, and CAC payback.",
    "What's your process for conducting sensitivity and Monte Carlo analysis?",
    "How do you approach foreign exchange risk management?",
    "Tell me about your experience with financial reporting and GAAP/IFRS standards.",
    "What's your approach to evaluating customer or market concentration risk?",
    "How do you model revenue recognition for complex contracts?",
    "Describe a time you supported a fundraising or capital raise process.",
    "What's your experience with hedge fund or investment banking?",
    "How do you approach credit analysis and lending decisions?",
    "Tell me about a time you performed post-acquisition integration analysis.",
    "What's your experience with financial systems like SAP, Oracle, or NetSuite?",
    "How do you evaluate portfolio diversification and asset allocation?",
    "Describe your approach to analyzing operating leverage and economies of scale.",
    "What's your experience with auditing or internal controls?"
  ],

  Consulting: [
    "Tell me about yourself and your consulting experience.",
    "How do you approach a new client engagement?",
    "Walk me through a case where you had to solve a complex business problem.",
    "Describe your experience with stakeholder management.",
    "How do you structure ambiguous problems?",
    "What frameworks do you use for business analysis?",
    "Tell me about a time you had to deliver difficult news to a client.",
    "How do you prioritize when working on multiple projects?",
    "What's your approach to data gathering and analysis?",
    "Describe a time your recommendations weren't implemented. What did you do?",
    "How do you build credibility with senior executives?",
    "What's your experience with change management?",
    "Tell me about a project where you exceeded client expectations.",
    "How do you handle tight deadlines and pressure?",
    "What's your approach to creating client presentations?",
    "Describe a time you had to learn about a new industry quickly.",
    "How do you ensure your recommendations are actionable?",
    "What's your experience with different consulting methodologies?",
    "Tell me about a time you worked with a difficult team member.",
    "How do you measure the success of a consulting engagement?",
    "What's your approach to competitive analysis?",
    "Describe a time you identified an unexpected opportunity for a client.",
    "How do you balance client demands with your firm's interests?",
    "What's your experience with digital transformation projects?",
    "Tell me about the most challenging problem you've solved in consulting.",
    "How do you approach market sizing and estimation questions?",
    "What's your experience with post-merger integration (PMI) work?",
    "Tell me about a time you had to influence without authority.",
    "How do you conduct due diligence for strategic investments?",
    "Describe your approach to organizational design and restructuring.",
    "What's your experience with commercial due diligence?",
    "How do you approach pricing strategy and optimization?",
    "Tell me about a time you managed scope creep on an engagement.",
    "What's your approach to building financial business cases?",
    "How do you handle situations where the client disagrees with your analysis?",
    "Describe your experience with cost reduction and operational efficiency projects.",
    "What's your process for conducting customer or market segmentation?",
    "How do you approach go-to-market strategy development?",
    "Tell me about a time you identified a critical insight that changed the project direction.",
    "What's your experience with transformation programs?",
    "How do you approach supply chain optimization projects?",
    "Describe a time you had to manage client expectations.",
    "What's your approach to building implementation roadmaps?",
    "How do you conduct benchmark analysis and best practice research?",
    "Tell me about your experience with agile or lean methodologies in consulting.",
    "What's your process for creating executive-level communications?",
    "How do you approach sales force effectiveness projects?",
    "Describe a time you led a cross-functional project team.",
    "What's your experience with private equity portfolio company work?",
    "How do you approach conducting expert interviews and primary research?"
  ],

  Operations: [
    "Tell me about yourself and your operations experience.",
    "How do you approach process improvement?",
    "Describe a time you increased operational efficiency.",
    "What metrics do you use to measure operational performance?",
    "How do you manage cross-functional teams?",
    "Tell me about a project where you had to manage competing priorities.",
    "What's your experience with lean or six sigma methodologies?",
    "How do you handle unexpected operational challenges?",
    "Describe your approach to resource allocation.",
    "What's your experience with supply chain management?",
    "How do you ensure quality while maintaining efficiency?",
    "Tell me about a time you implemented a new process or system.",
    "What's your approach to stakeholder communication?",
    "How do you manage risks in operations?",
    "Describe a time you had to scale operations quickly.",
    "What tools do you use for project management?",
    "How do you handle conflicts between teams?",
    "Tell me about your experience with vendor management.",
    "What's your approach to cost reduction without sacrificing quality?",
    "How do you measure and improve customer satisfaction?",
    "Describe a time you led a major operational change.",
    "What's your experience with data analysis in operations?",
    "How do you ensure compliance with regulations?",
    "Tell me about a time you had to make a difficult operational decision.",
    "What's your approach to continuous improvement?",
    "How do you approach capacity planning and demand forecasting?",
    "What's your experience with warehouse and logistics optimization?",
    "Tell me about a time you implemented automation to improve operations.",
    "How do you approach inventory management and optimization?",
    "Describe your experience with ERP systems like SAP or Oracle.",
    "What's your approach to building standard operating procedures (SOPs)?",
    "How do you manage production scheduling and planning?",
    "Tell me about a time you resolved a major supply chain disruption.",
    "What's your experience with quality assurance and control systems?",
    "How do you approach root cause analysis for operational failures?",
    "Describe a time you improved on-time delivery performance.",
    "What's your approach to network design and optimization?",
    "How do you manage third-party logistics (3PL) relationships?",
    "Tell me about your experience with manufacturing operations.",
    "What's your process for conducting time and motion studies?",
    "How do you approach workforce planning and labor optimization?",
    "Describe a time you led a kaizen or continuous improvement event.",
    "What's your experience with fulfillment center operations?",
    "How do you approach safety management and OSHA compliance?",
    "Tell me about a time you reduced operational costs significantly.",
    "What's your approach to managing reverse logistics and returns?",
    "How do you balance inventory levels with customer service expectations?",
    "Describe your experience with procurement and sourcing strategies.",
    "What's your approach to KPI development and performance dashboards?",
    "How do you manage operational transitions during peak seasons?"
  ],

  "Human Resources": [
    "Tell me about yourself and your HR experience.",
    "How do you approach talent acquisition strategy?",
    "Describe a time you resolved a difficult employee relations issue.",
    "What's your experience with performance management systems?",
    "How do you ensure diversity and inclusion in hiring?",
    "Tell me about a successful retention initiative you led.",
    "What's your approach to employee engagement?",
    "How do you handle confidential or sensitive situations?",
    "Describe your experience with compensation and benefits.",
    "What's your process for conducting effective interviews?",
    "How do you partner with business leaders on talent strategy?",
    "Tell me about a time you had to navigate a complex HR policy issue.",
    "What's your approach to organizational development?",
    "How do you measure HR effectiveness?",
    "Describe a time you improved an HR process.",
    "What's your experience with HRIS systems?",
    "How do you handle employee complaints or grievances?",
    "Tell me about your approach to onboarding new employees.",
    "What's your experience with change management from an HR perspective?",
    "How do you stay updated with employment laws and regulations?",
    "Describe a time you had to deliver difficult feedback.",
    "What's your approach to succession planning?",
    "How do you build relationships with employees at all levels?",
    "Tell me about a time you drove cultural change.",
    "What's your experience with learning and development programs?",
    "How do you approach conducting workplace investigations?",
    "What's your experience with executive compensation and equity packages?",
    "Tell me about a time you managed a reduction in force or layoff.",
    "How do you approach building employer branding?",
    "Describe your experience with union relations or collective bargaining.",
    "What's your approach to developing competency frameworks?",
    "How do you measure and improve diversity, equity, and inclusion metrics?",
    "Tell me about a time you designed a leadership development program.",
    "What's your experience with HR analytics and people data?",
    "How do you approach remote work policies and hybrid workforce management?",
    "Describe a time you handled a harassment or discrimination complaint.",
    "What's your approach to total rewards strategy?",
    "How do you conduct organizational health assessments?",
    "Tell me about your experience with applicant tracking systems (ATS).",
    "What's your process for conducting stay interviews and exit interviews?",
    "How do you approach talent review and calibration sessions?",
    "Describe a time you implemented a new HRIS or HR technology.",
    "What's your experience with employee wellness and mental health programs?",
    "How do you approach pay equity analysis and compliance?",
    "Tell me about a time you managed a complex termination or separation.",
    "What's your approach to building skills-based hiring practices?",
    "How do you design and implement performance improvement plans?",
    "Describe your experience with mergers and acquisitions from an HR perspective.",
    "What's your approach to internal mobility and career pathing?",
    "How do you handle whistleblower complaints or ethics violations?"
  ],

  Healthcare: [
    "Tell me about yourself and your background in healthcare.",
    "How do you ensure patient safety and quality of care?",
    "Describe your experience with healthcare regulations and compliance.",
    "What's your approach to working in interdisciplinary teams?",
    "How do you handle stressful or emergency situations?",
    "Tell me about a time you improved a healthcare process or outcome.",
    "What's your experience with electronic health records systems?",
    "How do you stay current with medical research and best practices?",
    "Describe a challenging patient case and how you handled it.",
    "What's your approach to patient communication?",
    "How do you balance efficiency with quality care?",
    "Tell me about your experience with clinical trials or research.",
    "What's your understanding of healthcare policy and reform?",
    "How do you handle ethical dilemmas in healthcare?",
    "Describe a time you advocated for a patient.",
    "What's your experience with healthcare data analysis?",
    "How do you approach continuous quality improvement?",
    "Tell me about a time you collaborated with other healthcare providers.",
    "What's your experience with medical device development or regulation?",
    "How do you ensure infection control and prevention?",
    "Describe your approach to healthcare administration.",
    "What's your experience with insurance and billing processes?",
    "How do you manage resources in a healthcare setting?",
    "Tell me about a time you dealt with a difficult situation with a patient or family.",
    "What's your vision for the future of healthcare?",
    "How do you approach value-based care and population health management?",
    "What's your experience with HIPAA compliance and patient privacy?",
    "Tell me about a time you reduced hospital readmissions or improved patient outcomes.",
    "How do you approach clinical decision support and evidence-based medicine?",
    "Describe your experience with telehealth or remote patient monitoring.",
    "What's your approach to managing patient wait times and throughput?",
    "How do you handle medical errors or adverse events?",
    "Tell me about your experience with quality metrics like HEDIS or CMS measures.",
    "What's your approach to care coordination across different settings?",
    "How do you address social determinants of health in patient care?",
    "Describe a time you implemented a patient safety initiative.",
    "What's your experience with healthcare analytics and predictive modeling?",
    "How do you approach medication reconciliation and reducing adverse drug events?",
    "Tell me about your experience with Joint Commission or other accreditation processes.",
    "What's your approach to managing healthcare workforce shortages?",
    "How do you implement clinical pathways or care protocols?",
    "Describe your experience with revenue cycle management.",
    "What's your approach to patient satisfaction and experience improvement?",
    "How do you handle end-of-life care and palliative care discussions?",
    "Tell me about a time you reduced healthcare costs while maintaining quality.",
    "What's your experience with health information technology implementation?",
    "How do you approach cultural competency in healthcare delivery?",
    "Describe your experience with clinical documentation improvement.",
    "What's your approach to managing physician-hospital relationships?",
    "How do you leverage AI or machine learning in healthcare applications?"
  ],

  Legal: [
    "Tell me about yourself and your legal background.",
    "Walk me through a complex legal matter you handled.",
    "How do you approach legal research?",
    "Describe your experience with contract negotiation.",
    "What's your process for staying updated with legal developments?",
    "How do you communicate complex legal concepts to non-lawyers?",
    "Tell me about a time you had to work under a tight deadline.",
    "What's your experience with litigation?",
    "How do you prioritize when managing multiple matters?",
    "Describe a time you identified a legal risk that others missed.",
    "What's your approach to client counseling?",
    "How do you handle ethical dilemmas in legal practice?",
    "Tell me about your experience with regulatory compliance.",
    "What's your approach to alternative dispute resolution?",
    "How do you manage relationships with opposing counsel?",
    "Describe a time you had to deliver unfavorable legal advice.",
    "What's your experience with corporate governance?",
    "How do you ensure accuracy in your legal work?",
    "Tell me about a particularly challenging case you worked on.",
    "What's your approach to legal writing?",
    "How do you work with internal business stakeholders?",
    "Describe your experience with mergers and acquisitions.",
    "What's your understanding of our industry's legal landscape?",
    "How do you handle high-pressure situations?",
    "Tell me about a time you negotiated a favorable outcome.",
    "How do you approach intellectual property strategy and protection?",
    "What's your experience with privacy law and data protection (GDPR, CCPA)?",
    "Tell me about a time you managed a bet-the-company litigation.",
    "How do you approach employment law issues and workplace investigations?",
    "Describe your experience with securities law and public company matters.",
    "What's your approach to managing outside counsel relationships?",
    "How do you handle crisis management and internal investigations?",
    "Tell me about your experience with antitrust and competition law.",
    "What's your approach to building legal templates and playbooks?",
    "How do you assess legal risk in commercial transactions?",
    "Describe a time you negotiated complex commercial agreements.",
    "What's your experience with international law and cross-border transactions?",
    "How do you approach legal technology and contract lifecycle management?",
    "Tell me about a time you managed discovery in high-stakes litigation.",
    "What's your experience with environmental or regulatory law?",
    "How do you approach board governance and fiduciary duties?",
    "Describe your experience with financing transactions and capital markets.",
    "What's your approach to managing legal budgets and cost control?",
    "How do you handle settlement negotiations and mediation?",
    "Tell me about your experience with open source licensing or technology law.",
    "What's your approach to conducting legal due diligence?",
    "How do you manage trademark, patent, or copyright portfolios?",
    "Describe a time you drafted or negotiated a key partnership agreement.",
    "What's your experience with litigation strategy and trial preparation?",
    "How do you approach legal risk assessment for new business initiatives?"
  ],

  Creative: [
    "Tell me about yourself and your creative background.",
    "Walk me through your creative process.",
    "How do you handle creative blocks?",
    "Describe a project where you had to meet specific brand guidelines.",
    "What's your experience with different creative tools and software?",
    "How do you incorporate feedback into your creative work?",
    "Tell me about a campaign or project you're particularly proud of.",
    "What's your approach to staying inspired and generating new ideas?",
    "How do you balance creativity with business objectives?",
    "Describe a time you had to work with a difficult client or stakeholder.",
    "What's your experience with content strategy?",
    "How do you measure the success of creative work?",
    "Tell me about a time a creative project didn't go as planned.",
    "What's your approach to collaboration with other creatives?",
    "How do you stay updated with creative trends?",
    "Describe your experience with multimedia content creation.",
    "What's your process for developing creative concepts?",
    "How do you manage multiple projects with different deadlines?",
    "Tell me about a time you pushed creative boundaries.",
    "What's your experience with brand development?",
    "How do you approach audience targeting in creative work?",
    "Describe a time you had to adapt your creative style.",
    "What's your experience with social media content?",
    "How do you handle criticism of your creative work?",
    "Tell me about your approach to storytelling.",
    "How do you approach creative concepting for integrated campaigns?",
    "What's your experience with motion graphics and animation?",
    "Tell me about a time you led a creative brainstorming session.",
    "How do you balance brand consistency with creative innovation?",
    "Describe your experience with photography or videography direction.",
    "What's your approach to creative testing and optimization?",
    "How do you collaborate with copywriters and art directors?",
    "Tell me about a time you turned around a failing creative campaign.",
    "What's your experience with Adobe Creative Suite or similar tools?",
    "How do you approach creative for different platforms and formats?",
    "Describe a time you created content that went viral or had massive reach.",
    "What's your process for creative pitches and client presentations?",
    "How do you approach influencer creative and partnerships?",
    "Tell me about your experience with 3D design or AR/VR content.",
    "What's your approach to accessibility in creative work?",
    "How do you manage creative production timelines and budgets?",
    "Describe a time you had to create under extreme time constraints.",
    "What's your experience with user-generated content campaigns?",
    "How do you approach creative localization for global markets?",
    "Tell me about a time you mentored junior creatives.",
    "What's your process for building mood boards and visual direction?",
    "How do you balance data-driven insights with creative intuition?",
    "Describe your experience with podcast or audio content creation.",
    "What's your approach to creating inclusive and diverse creative work?",
    "How do you stay creatively fresh while maintaining brand voice?"
  ],

  Engineering: [
    "Tell me about yourself and your engineering background.",
    "Walk me through a complex engineering project you led.",
    "How do you approach problem-solving in engineering?",
    "Describe your experience with CAD or design software.",
    "What's your process for ensuring safety and compliance?",
    "How do you stay updated with engineering standards and regulations?",
    "Tell me about a time you had to optimize a design or process.",
    "What's your experience with project management in engineering?",
    "How do you handle technical challenges or setbacks?",
    "Describe a time you had to work within budget constraints.",
    "What's your approach to testing and validation?",
    "How do you collaborate with other engineering disciplines?",
    "Tell me about your experience with manufacturing processes.",
    "What's your approach to documentation and specifications?",
    "How do you balance innovation with practical constraints?",
    "Describe a time you improved an existing system or design.",
    "What's your experience with quality control?",
    "How do you communicate technical information to non-engineers?",
    "Tell me about a project where you had to meet strict deadlines.",
    "What's your approach to sustainability in engineering?",
    "How do you manage risks in engineering projects?",
    "Describe your experience with prototyping and iteration.",
    "What tools and methodologies do you use in your work?",
    "How do you ensure your designs are cost-effective?",
    "Tell me about the most challenging engineering problem you've solved.",
    "How do you approach finite element analysis (FEA) and simulation?",
    "What's your experience with Design for Manufacturing (DFM)?",
    "Tell me about a time you led a design review or technical critique.",
    "How do you approach failure mode and effects analysis (FMEA)?",
    "Describe your experience with additive manufacturing or 3D printing.",
    "What's your approach to tolerance analysis and GD&T?",
    "How do you handle design changes late in the development cycle?",
    "Tell me about your experience with thermal management or fluid dynamics.",
    "What's your process for conducting root cause analysis on failures?",
    "How do you approach design validation and verification (DVT/PVT)?",
    "Describe a time you optimized a product for cost reduction.",
    "What's your experience with embedded systems or firmware development?",
    "How do you approach materials selection for engineering applications?",
    "Tell me about your experience with regulatory testing (UL, CE, FCC).",
    "What's your approach to design for reliability and durability?",
    "How do you manage engineering change orders (ECOs)?",
    "Describe your experience with mechatronics or electromechanical systems.",
    "What's your process for conducting design of experiments (DOE)?",
    "How do you approach supply chain collaboration for new product introduction?",
    "Tell me about a time you solved a critical field failure issue.",
    "What's your experience with PLM (Product Lifecycle Management) systems?",
    "How do you approach design for assembly (DFA) principles?",
    "Describe your experience with MATLAB, Python, or other engineering tools.",
    "What's your approach to patent applications and IP protection?",
    "How do you balance performance requirements with manufacturability?"
  ],

  Cybersecurity: [
    "Tell me about yourself and your cybersecurity background.",
    "Walk me through how you would respond to a security breach.",
    "What frameworks and standards do you use in security? (NIST, ISO 27001, etc.)",
    "Describe a time you identified and mitigated a critical security vulnerability.",
    "How do you stay current with emerging threats and attack vectors?",
    "What's your approach to conducting a penetration test?",
    "Tell me about your experience with SIEM tools and log analysis.",
    "How do you prioritize security vulnerabilities for remediation?",
    "Describe your experience with incident response and forensics.",
    "What's your approach to threat hunting?",
    "How do you balance security requirements with business needs?",
    "Tell me about a time you had to explain a security risk to non-technical stakeholders.",
    "What's your experience with cloud security? (AWS, Azure, GCP)",
    "How do you approach application security testing?",
    "Describe your experience with security automation and orchestration.",
    "What's your process for conducting security risk assessments?",
    "How do you handle zero-day vulnerabilities?",
    "Tell me about your experience with network security and firewalls.",
    "What's your approach to identity and access management?",
    "How do you test and validate security controls?",
    "Describe a time you implemented a security solution that improved the organization's posture.",
    "What's your experience with compliance frameworks? (SOC 2, PCI DSS, HIPAA, GDPR)",
    "How do you approach security awareness training?",
    "Tell me about a time you had to work under pressure during a security incident.",
    "What tools do you use for vulnerability scanning and management?",
    "How do you perform malware analysis?",
    "Describe your experience with red team or blue team operations.",
    "What's your approach to securing CI/CD pipelines?",
    "How do you handle insider threats?",
    "Tell me about the most challenging security incident you've responded to.",
    "How do you approach container security and Kubernetes hardening?",
    "What's your experience with threat intelligence platforms and feeds?",
    "Tell me about a time you conducted a tabletop exercise or disaster recovery drill.",
    "How do you approach API security and authentication mechanisms?",
    "Describe your experience with endpoint detection and response (EDR) tools.",
    "What's your approach to security architecture review for new systems?",
    "How do you handle ransomware prevention and response?",
    "Tell me about your experience with cryptography and encryption standards.",
    "What's your process for conducting purple team exercises?",
    "How do you approach zero trust security architecture?",
    "Describe a time you built security metrics and reporting for leadership.",
    "What's your experience with supply chain security and third-party risk?",
    "How do you approach secrets management and credential rotation?",
    "Tell me about your experience with security orchestration, automation, and response (SOAR).",
    "What's your approach to mobile application security testing?",
    "How do you conduct threat modeling for applications?",
    "Describe your experience with security incident post-mortems.",
    "What's your approach to managing bug bounty programs?",
    "How do you handle security in DevSecOps environments?",
    "Tell me about a time you improved security without disrupting business operations."
  ],

  Hospitality: [
    "Tell me about yourself and your experience in hospitality.",
    "How do you handle difficult or unhappy guests?",
    "Describe a time you went above and beyond for a customer.",
    "What's your approach to managing multiple events or bookings simultaneously?",
    "How do you stay organized when coordinating complex travel arrangements?",
    "Tell me about a time you had to resolve a last-minute crisis.",
    "How do you build relationships with vendors and partners?",
    "What destination expertise do you bring to this role?",
    "How do you ensure exceptional guest experiences?",
    "Describe your experience with event budgeting and cost management.",
    "How do you handle cultural sensitivities when planning international travel?",
    "Tell me about a successful event you've coordinated from start to finish.",
    "What booking systems and travel technology are you familiar with?",
    "How do you stay updated on travel trends and new destinations?",
    "Describe a time you had to manage competing client priorities.",
    "How do you measure success in hospitality and events?",
    "Tell me about your negotiation experience with hotels and venues.",
    "How do you create personalized experiences for different types of travelers?",
    "What's your approach to risk management in event planning?",
    "How do you handle feedback and complaints professionally?",
    "How do you approach revenue management and dynamic pricing?",
    "What's your experience with property management systems (PMS)?",
    "Tell me about a time you increased guest satisfaction scores.",
    "How do you handle staffing and scheduling for peak periods?",
    "Describe your experience with food and beverage operations.",
    "What's your approach to training and developing hospitality staff?",
    "How do you manage inventory and procurement for hospitality operations?",
    "Tell me about a time you recovered from a service failure.",
    "What's your experience with corporate event planning and execution?",
    "How do you approach sustainable and eco-friendly hospitality practices?",
    "Describe a time you managed a VIP or high-profile client.",
    "What's your process for quality assurance and service standards?",
    "How do you leverage technology to enhance guest experiences?",
    "Tell me about your experience with wedding or destination event planning.",
    "What's your approach to crisis management in hospitality settings?",
    "How do you handle overbooking or capacity issues?",
    "Describe your experience with loyalty programs and guest retention.",
    "What's your approach to managing online reviews and reputation?",
    "How do you coordinate with destination management companies (DMCs)?",
    "Tell me about a time you planned an event with complex logistics.",
    "What's your experience with conference and convention planning?",
    "How do you approach accessibility and inclusive hospitality?",
    "Describe your experience with hotel sales and group bookings.",
    "What's your process for post-event evaluation and client follow-up?",
    "How do you manage multiple stakeholders in large events?",
    "Tell me about your experience with luxury hospitality and concierge services.",
    "What's your approach to handling guest privacy and data security?",
    "How do you build strategic partnerships with airlines and travel suppliers?",
    "Describe a time you innovated to improve guest experiences.",
    "What's your experience with hospitality analytics and performance metrics?"
  ],

  "Public Sector": [
    "Tell me about your experience working in public service or non-profit organizations.",
    "How do you develop effective workforce training programs?",
    "Describe your grant writing experience and success rate.",
    "What's your approach to community engagement and stakeholder management?",
    "How do you measure program impact and effectiveness?",
    "Tell me about a time you had to navigate government regulations and compliance.",
    "How do you manage budgets in resource-constrained environments?",
    "Describe your experience with public policy development.",
    "How do you build partnerships with employers and community organizations?",
    "What research methods do you use for policy analysis?",
    "Tell me about a challenging grant proposal you've written.",
    "How do you ensure equitable access to your programs and services?",
    "Describe your experience with urban planning or community development.",
    "How do you balance competing stakeholder interests?",
    "What's your approach to volunteer management and coordination?",
    "How do you communicate complex policy issues to diverse audiences?",
    "Tell me about a successful program you developed and implemented.",
    "How do you stay informed about funding opportunities?",
    "Describe your experience with data-driven decision making in public programs.",
    "What motivates you to work in public service?",
    "How do you approach performance measurement for government programs?",
    "What's your experience with procurement and contracting processes?",
    "Tell me about a time you led a public consultation or town hall meeting.",
    "How do you manage political sensitivity in public sector work?",
    "Describe your experience with legislative processes and advocacy.",
    "What's your approach to program evaluation and outcomes measurement?",
    "How do you handle transparency and public records requests?",
    "Tell me about a time you secured federal or state funding.",
    "What's your experience with coalition building across sectors?",
    "How do you approach economic development initiatives?",
    "Describe a time you implemented policy change at scale.",
    "What's your experience with environmental or sustainability policy?",
    "How do you approach needs assessment for community programs?",
    "Tell me about your experience with emergency management or disaster response.",
    "What's your approach to managing cross-agency collaboration?",
    "How do you ensure accountability in public programs?",
    "Describe your experience with constituent services and case management.",
    "What's your process for conducting impact evaluations?",
    "How do you approach diversity, equity, and inclusion in public service?",
    "Tell me about a time you improved government efficiency or reduced costs.",
    "What's your experience with public health programs or social services?",
    "How do you manage relationships with elected officials?",
    "Describe your experience with education policy or K-12 programs.",
    "What's your approach to using data visualization for public reporting?",
    "How do you handle competing priorities with limited resources?",
    "Tell me about your experience with infrastructure planning and development.",
    "What's your approach to civic engagement and voter participation?",
    "How do you navigate bureaucracy to implement innovative solutions?",
    "Describe your experience with housing policy or affordable housing programs.",
    "What's your vision for effective and equitable public service?"
  ],

  Sustainability: [
    "Tell me about your passion for sustainability and environmental work.",
    "How do you measure and track carbon emissions?",
    "Describe your experience with ESG (Environmental, Social, Governance) frameworks.",
    "What sustainability certifications are you familiar with? (LEED, B Corp, etc.)",
    "How do you communicate the business case for sustainability initiatives?",
    "Tell me about a successful sustainability program you've implemented.",
    "How do you stay updated on climate science and environmental regulations?",
    "Describe your experience with renewable energy projects.",
    "How do you engage stakeholders in sustainability efforts?",
    "What metrics do you use to measure sustainability performance?",
    "Tell me about a time you had to overcome resistance to green initiatives.",
    "How do you conduct life cycle assessments?",
    "Describe your experience with sustainability reporting standards (GRI, CDP, etc.).",
    "How do you balance environmental goals with business objectives?",
    "What's your approach to circular economy principles?",
    "Tell me about your experience with climate risk assessment.",
    "How do you calculate scope 1, 2, and 3 emissions?",
    "Describe a time you identified cost savings through sustainability measures.",
    "What renewable energy technologies are you most familiar with?",
    "How do you promote sustainable behavior change in organizations?",
    "How do you approach developing net-zero or carbon neutrality strategies?",
    "What's your experience with sustainable supply chain management?",
    "Tell me about a time you conducted materiality assessments for ESG.",
    "How do you approach water stewardship and resource conservation?",
    "Describe your experience with green building and LEED certification.",
    "What's your approach to waste reduction and zero-waste initiatives?",
    "How do you evaluate and select carbon offset or renewable energy credit programs?",
    "Tell me about your experience with climate scenario analysis (TCFD).",
    "What's your process for stakeholder engagement on ESG issues?",
    "How do you approach biodiversity and ecosystem protection?",
    "Describe a time you integrated sustainability into product design.",
    "What's your experience with sustainable finance and green bonds?",
    "How do you measure social impact alongside environmental impact?",
    "Tell me about your experience with science-based targets (SBTi).",
    "What's your approach to sustainable procurement policies?",
    "How do you handle greenwashing concerns and ensure authentic commitments?",
    "Describe your experience with environmental impact assessments.",
    "What's your approach to employee engagement in sustainability programs?",
    "How do you track progress toward UN Sustainable Development Goals (SDGs)?",
    "Tell me about a time you partnered with NGOs or environmental organizations.",
    "What's your experience with renewable energy procurement (PPAs)?",
    "How do you approach climate adaptation and resilience planning?",
    "Describe your experience with sustainable packaging initiatives.",
    "What's your process for conducting environmental audits?",
    "How do you approach diversity and social equity in sustainability work?",
    "Tell me about your experience with energy efficiency programs.",
    "What's your approach to measuring and reducing embodied carbon?",
    "How do you leverage technology and data for sustainability tracking?",
    "Describe a time you influenced C-suite leadership on climate action.",
    "What's your vision for corporate sustainability in the next decade?"
  ],

  "Real Estate": [
    "Tell me about your real estate experience and specialization.",
    "How do you evaluate property investment opportunities?",
    "Describe your approach to property valuation and market analysis.",
    "What's your experience with commercial vs. residential real estate?",
    "How do you build and maintain relationships with property owners?",
    "Tell me about a complex negotiation you've handled.",
    "How do you conduct due diligence on property acquisitions?",
    "Describe your experience with property management.",
    "What market research tools and databases do you use?",
    "How do you assess location and development potential?",
    "Tell me about a challenging deal you closed.",
    "How do you stay informed about real estate market trends?",
    "Describe your experience with financing and capital raising.",
    "What's your approach to tenant relations and retention?",
    "How do you manage property maintenance and operations?",
    "Tell me about your experience with zoning and land use regulations.",
    "How do you create financial models for real estate investments?",
    "Describe a time you identified an undervalued property opportunity.",
    "What property management software are you familiar with?",
    "How do you handle property disputes or difficult situations?",
    "How do you approach cap rate analysis and yield calculations?",
    "What's your experience with 1031 exchanges and tax strategies?",
    "Tell me about a time you managed a distressed property or workout situation.",
    "How do you evaluate mixed-use development opportunities?",
    "Describe your experience with real estate development from ground up.",
    "What's your approach to lease negotiations and structuring?",
    "How do you assess market cycles and timing for acquisitions?",
    "Tell me about your experience with REIT management or investment.",
    "What's your process for underwriting real estate deals?",
    "How do you approach asset repositioning and value-add strategies?",
    "Describe a time you navigated environmental issues or remediation.",
    "What's your experience with multifamily property management?",
    "How do you analyze comparable sales and rental comps?",
    "Tell me about your experience with construction management.",
    "What's your approach to managing investor relations?",
    "How do you handle lease-up strategies for new properties?",
    "Describe your experience with retail, office, or industrial properties.",
    "What's your process for conducting market feasibility studies?",
    "How do you approach property tax appeals and assessments?",
    "Tell me about a time you managed a portfolio of properties.",
    "What's your experience with real estate syndication?",
    "How do you evaluate ESG factors in real estate investments?",
    "Describe your approach to property disposition and exit strategies.",
    "What's your experience with affordable housing or HUD programs?",
    "How do you handle tenant default or eviction situations?",
    "Tell me about your experience with real estate private equity.",
    "What's your approach to analyzing operating expenses and NOI?",
    "How do you leverage technology and proptech in real estate?",
    "Describe a time you restructured debt on a property.",
    "What's your vision for the future of real estate investing?"
  ]
};

// General questions that apply to all roles
export const generalQuestions: string[] = [
  "Tell me about yourself.",
  "Why are you interested in this position?",
  "What are your greatest strengths?",
  "What are your areas for improvement?",
  "Where do you see yourself in 5 years?",
  "Why do you want to work for our company?",
  "Tell me about a time you failed and what you learned.",
  "How do you handle stress and pressure?",
  "What motivates you?",
  "Do you have any questions for me?"
];

export function getQuestionsForRole(category: string): string[] {
  const categoryQuestions = questionsByCategory[category] || questionsByCategory['Technology'];
  const allQuestions = [...generalQuestions, ...categoryQuestions];

  // Shuffle and return 45 questions
  return allQuestions.sort(() => Math.random() - 0.5).slice(0, 45);
}
