export const questionsByCategory: Record<string, string[]> = {
  Technology: [
    "Tell me about yourself and your experience in software development.",
    "Walk me through a complex technical problem you solved recently.",
    "How do you approach system design for scalable applications?",
    "Describe your experience with our tech stack.",
    "What's your process for code review and ensuring code quality?",
    "How do you stay updated with new technologies and frameworks?",
    "Tell me about a time you had to debug a critical production issue.",
    "How do you handle technical debt in your projects?",
    "Describe your experience with microservices architecture.",
    "What's your approach to writing unit tests and achieving good test coverage?",
    "How do you optimize application performance?",
    "Tell me about a disagreement you had with a team member about a technical decision.",
    "What's your experience with CI/CD pipelines?",
    "How do you ensure security best practices in your code?",
    "Describe a time you had to learn a new technology quickly.",
    "What's your approach to documentation?",
    "How do you balance technical excellence with meeting deadlines?",
    "Tell me about a project where you improved existing code or infrastructure.",
    "What metrics do you use to measure code quality?",
    "How do you mentor junior developers?",
    "Describe your experience working in an agile environment.",
    "What's your approach to handling legacy code?",
    "How do you prioritize technical improvements versus new features?",
    "Tell me about a time you made a significant architectural decision.",
    "What's your experience with cloud platforms like AWS, Azure, or GCP?"
  ],

  "Data Science": [
    "Tell me about yourself and your background in data science.",
    "Walk me through a machine learning project from start to finish.",
    "How do you approach feature engineering?",
    "What's your experience with different ML algorithms and when to use each?",
    "Describe a time when your model didn't perform well. How did you improve it?",
    "How do you handle imbalanced datasets?",
    "What's your process for validating model performance?",
    "Tell me about your experience with A/B testing.",
    "How do you explain complex statistical concepts to non-technical stakeholders?",
    "What's your approach to data cleaning and preprocessing?",
    "Describe your experience with big data technologies.",
    "How do you prevent overfitting in your models?",
    "What evaluation metrics do you use and why?",
    "Tell me about a time you had to work with messy or incomplete data.",
    "How do you approach exploratory data analysis?",
    "What's your experience with deep learning frameworks?",
    "How do you ensure your models are production-ready?",
    "Describe a time you used data to drive a business decision.",
    "What's your experience with time series analysis?",
    "How do you handle missing data?",
    "Tell me about your experience with data visualization tools.",
    "What's your approach to model deployment and monitoring?",
    "How do you stay current with new ML techniques and research?",
    "Describe a challenging data problem you solved.",
    "What's your experience with SQL and database querying?"
  ],

  Product: [
    "Tell me about yourself and your product management experience.",
    "How do you prioritize features in a product roadmap?",
    "Walk me through how you would launch a new product.",
    "Describe a time when you had to say no to a feature request.",
    "How do you gather and incorporate user feedback?",
    "What frameworks do you use for product prioritization?",
    "Tell me about a product you managed from conception to launch.",
    "How do you work with engineering teams to define requirements?",
    "What metrics do you track to measure product success?",
    "Describe a time when a product launch didn't go as planned.",
    "How do you balance user needs with business goals?",
    "What's your approach to competitive analysis?",
    "Tell me about a time you had to pivot a product strategy.",
    "How do you conduct user research?",
    "What's your experience with A/B testing and experimentation?",
    "Describe how you would improve one of our products.",
    "How do you create and communicate product vision?",
    "Tell me about a time you disagreed with stakeholders about product direction.",
    "What's your process for writing product requirements documents?",
    "How do you manage multiple stakeholders with conflicting priorities?",
    "Describe your experience with agile product development.",
    "What's your approach to technical debt as a PM?",
    "How do you measure product-market fit?",
    "Tell me about a data-driven decision you made as a PM.",
    "What's your experience with go-to-market strategy?"
  ],

  Design: [
    "Tell me about yourself and your design background.",
    "Walk me through your design process from research to final delivery.",
    "How do you approach user research?",
    "Describe a challenging design problem you solved.",
    "How do you handle feedback and criticism of your designs?",
    "What's your experience with design systems?",
    "Tell me about a time you had to advocate for the user.",
    "How do you balance aesthetics with usability?",
    "What's your process for creating wireframes and prototypes?",
    "Describe a time when you had to design under tight constraints.",
    "How do you measure the success of your designs?",
    "What tools do you use and why?",
    "Tell me about a time you collaborated with developers on implementation.",
    "How do you stay updated with design trends?",
    "What's your approach to accessibility in design?",
    "Describe a project where you improved an existing user experience.",
    "How do you conduct usability testing?",
    "Tell me about a time you had to compromise on a design.",
    "What's your experience with mobile vs web design?",
    "How do you present and justify your design decisions?",
    "Describe your experience with design thinking methodologies.",
    "What's your approach to creating personas and user journeys?",
    "How do you handle conflicting feedback from stakeholders?",
    "Tell me about a design that you're particularly proud of.",
    "What's your process for iterating on designs based on data?"
  ],

  Marketing: [
    "Tell me about yourself and your marketing experience.",
    "How do you develop a marketing strategy for a new product?",
    "What metrics do you use to measure campaign success?",
    "Describe a successful marketing campaign you led.",
    "How do you identify and reach your target audience?",
    "What's your experience with digital marketing channels?",
    "Tell me about a campaign that didn't perform well and what you learned.",
    "How do you allocate marketing budget across channels?",
    "What's your approach to content marketing?",
    "Describe your experience with marketing automation tools.",
    "How do you work with sales teams to generate qualified leads?",
    "What's your process for conducting market research?",
    "Tell me about your experience with SEO and SEM.",
    "How do you measure ROI on marketing spend?",
    "What's your approach to building brand awareness?",
    "Describe a time you had to pivot a marketing strategy.",
    "How do you use data to inform marketing decisions?",
    "What's your experience with social media marketing?",
    "Tell me about a time you successfully increased customer acquisition.",
    "How do you create customer personas?",
    "What's your approach to email marketing?",
    "Describe your experience with influencer or partnership marketing.",
    "How do you stay updated with marketing trends?",
    "What's your experience with analytics tools like Google Analytics?",
    "Tell me about a time you had to work with a limited budget."
  ],

  Sales: [
    "Tell me about yourself and your sales experience.",
    "Walk me through your sales process from prospecting to close.",
    "How do you handle objections during a sales call?",
    "Describe your biggest sale and how you closed it.",
    "What's your approach to building rapport with prospects?",
    "How do you research prospects before reaching out?",
    "Tell me about a time you lost a deal. What did you learn?",
    "What metrics do you track to measure your sales performance?",
    "How do you manage your sales pipeline?",
    "Describe a time you exceeded your quota. How did you do it?",
    "What's your experience with CRM tools?",
    "How do you stay motivated during slow periods?",
    "Tell me about a complex B2B sale you navigated.",
    "What's your approach to cold calling or cold emailing?",
    "How do you handle pricing negotiations?",
    "Describe your experience with consultative selling.",
    "What's your strategy for upselling or cross-selling?",
    "How do you qualify leads effectively?",
    "Tell me about a time you turned a rejection into a sale.",
    "What's your approach to following up with prospects?",
    "How do you collaborate with marketing to generate leads?",
    "Describe a time you helped a customer solve a problem.",
    "What's your experience selling our type of product or service?",
    "How do you build long-term relationships with clients?",
    "Tell me about your most challenging sales negotiation."
  ],

  Finance: [
    "Tell me about yourself and your finance background.",
    "Walk me through a financial model you've built.",
    "How do you approach financial analysis and forecasting?",
    "Describe a time you identified a significant cost-saving opportunity.",
    "What's your experience with financial statements analysis?",
    "How do you evaluate investment opportunities?",
    "Tell me about a complex financial problem you solved.",
    "What metrics do you focus on when analyzing a company's performance?",
    "Describe your experience with budgeting and variance analysis.",
    "How do you stay updated with financial markets and regulations?",
    "What's your approach to risk assessment?",
    "Tell me about a time you presented financial findings to non-finance stakeholders.",
    "How do you ensure accuracy in your financial analysis?",
    "What's your experience with financial modeling tools?",
    "Describe a time you had to work under a tight deadline.",
    "How do you approach due diligence for M&A transactions?",
    "What's your understanding of valuation methodologies?",
    "Tell me about your experience with Excel and financial software.",
    "How do you handle conflicting priorities?",
    "What's your approach to scenario analysis?",
    "Describe a time you disagreed with a financial decision.",
    "How do you evaluate financial risks?",
    "What's your experience with regulatory compliance?",
    "Tell me about a project where your analysis drove key decisions.",
    "How do you approach cash flow analysis?"
  ],

  Consulting: [
    "Tell me about yourself and your consulting experience.",
    "How do you approach a new client engagement?",
    "Walk me through a case where you had to solve a complex business problem.",
    "Describe your experience with stakeholder management.",
    "How do you structure ambiguous problems?",
    "What frameworks do you use for business analysis?",
    "Tell me about a time you had to deliver difficult news to a client.",
    "How do you prioritize when working on multiple projects?",
    "What's your approach to data gathering and analysis?",
    "Describe a time your recommendations weren't implemented. What did you do?",
    "How do you build credibility with senior executives?",
    "What's your experience with change management?",
    "Tell me about a project where you exceeded client expectations.",
    "How do you handle tight deadlines and pressure?",
    "What's your approach to creating client presentations?",
    "Describe a time you had to learn about a new industry quickly.",
    "How do you ensure your recommendations are actionable?",
    "What's your experience with different consulting methodologies?",
    "Tell me about a time you worked with a difficult team member.",
    "How do you measure the success of a consulting engagement?",
    "What's your approach to competitive analysis?",
    "Describe a time you identified an unexpected opportunity for a client.",
    "How do you balance client demands with your firm's interests?",
    "What's your experience with digital transformation projects?",
    "Tell me about the most challenging problem you've solved in consulting."
  ],

  Operations: [
    "Tell me about yourself and your operations experience.",
    "How do you approach process improvement?",
    "Describe a time you increased operational efficiency.",
    "What metrics do you use to measure operational performance?",
    "How do you manage cross-functional teams?",
    "Tell me about a project where you had to manage competing priorities.",
    "What's your experience with lean or six sigma methodologies?",
    "How do you handle unexpected operational challenges?",
    "Describe your approach to resource allocation.",
    "What's your experience with supply chain management?",
    "How do you ensure quality while maintaining efficiency?",
    "Tell me about a time you implemented a new process or system.",
    "What's your approach to stakeholder communication?",
    "How do you manage risks in operations?",
    "Describe a time you had to scale operations quickly.",
    "What tools do you use for project management?",
    "How do you handle conflicts between teams?",
    "Tell me about your experience with vendor management.",
    "What's your approach to cost reduction without sacrificing quality?",
    "How do you measure and improve customer satisfaction?",
    "Describe a time you led a major operational change.",
    "What's your experience with data analysis in operations?",
    "How do you ensure compliance with regulations?",
    "Tell me about a time you had to make a difficult operational decision.",
    "What's your approach to continuous improvement?"
  ],

  "Human Resources": [
    "Tell me about yourself and your HR experience.",
    "How do you approach talent acquisition strategy?",
    "Describe a time you resolved a difficult employee relations issue.",
    "What's your experience with performance management systems?",
    "How do you ensure diversity and inclusion in hiring?",
    "Tell me about a successful retention initiative you led.",
    "What's your approach to employee engagement?",
    "How do you handle confidential or sensitive situations?",
    "Describe your experience with compensation and benefits.",
    "What's your process for conducting effective interviews?",
    "How do you partner with business leaders on talent strategy?",
    "Tell me about a time you had to navigate a complex HR policy issue.",
    "What's your approach to organizational development?",
    "How do you measure HR effectiveness?",
    "Describe a time you improved an HR process.",
    "What's your experience with HRIS systems?",
    "How do you handle employee complaints or grievances?",
    "Tell me about your approach to onboarding new employees.",
    "What's your experience with change management from an HR perspective?",
    "How do you stay updated with employment laws and regulations?",
    "Describe a time you had to deliver difficult feedback.",
    "What's your approach to succession planning?",
    "How do you build relationships with employees at all levels?",
    "Tell me about a time you drove cultural change.",
    "What's your experience with learning and development programs?"
  ],

  Healthcare: [
    "Tell me about yourself and your background in healthcare.",
    "How do you ensure patient safety and quality of care?",
    "Describe your experience with healthcare regulations and compliance.",
    "What's your approach to working in interdisciplinary teams?",
    "How do you handle stressful or emergency situations?",
    "Tell me about a time you improved a healthcare process or outcome.",
    "What's your experience with electronic health records systems?",
    "How do you stay current with medical research and best practices?",
    "Describe a challenging patient case and how you handled it.",
    "What's your approach to patient communication?",
    "How do you balance efficiency with quality care?",
    "Tell me about your experience with clinical trials or research.",
    "What's your understanding of healthcare policy and reform?",
    "How do you handle ethical dilemmas in healthcare?",
    "Describe a time you advocated for a patient.",
    "What's your experience with healthcare data analysis?",
    "How do you approach continuous quality improvement?",
    "Tell me about a time you collaborated with other healthcare providers.",
    "What's your experience with medical device development or regulation?",
    "How do you ensure infection control and prevention?",
    "Describe your approach to healthcare administration.",
    "What's your experience with insurance and billing processes?",
    "How do you manage resources in a healthcare setting?",
    "Tell me about a time you dealt with a difficult situation with a patient or family.",
    "What's your vision for the future of healthcare?"
  ],

  Legal: [
    "Tell me about yourself and your legal background.",
    "Walk me through a complex legal matter you handled.",
    "How do you approach legal research?",
    "Describe your experience with contract negotiation.",
    "What's your process for staying updated with legal developments?",
    "How do you communicate complex legal concepts to non-lawyers?",
    "Tell me about a time you had to work under a tight deadline.",
    "What's your experience with litigation?",
    "How do you prioritize when managing multiple matters?",
    "Describe a time you identified a legal risk that others missed.",
    "What's your approach to client counseling?",
    "How do you handle ethical dilemmas in legal practice?",
    "Tell me about your experience with regulatory compliance.",
    "What's your approach to alternative dispute resolution?",
    "How do you manage relationships with opposing counsel?",
    "Describe a time you had to deliver unfavorable legal advice.",
    "What's your experience with corporate governance?",
    "How do you ensure accuracy in your legal work?",
    "Tell me about a particularly challenging case you worked on.",
    "What's your approach to legal writing?",
    "How do you work with internal business stakeholders?",
    "Describe your experience with mergers and acquisitions.",
    "What's your understanding of our industry's legal landscape?",
    "How do you handle high-pressure situations?",
    "Tell me about a time you negotiated a favorable outcome."
  ],

  Creative: [
    "Tell me about yourself and your creative background.",
    "Walk me through your creative process.",
    "How do you handle creative blocks?",
    "Describe a project where you had to meet specific brand guidelines.",
    "What's your experience with different creative tools and software?",
    "How do you incorporate feedback into your creative work?",
    "Tell me about a campaign or project you're particularly proud of.",
    "What's your approach to staying inspired and generating new ideas?",
    "How do you balance creativity with business objectives?",
    "Describe a time you had to work with a difficult client or stakeholder.",
    "What's your experience with content strategy?",
    "How do you measure the success of creative work?",
    "Tell me about a time a creative project didn't go as planned.",
    "What's your approach to collaboration with other creatives?",
    "How do you stay updated with creative trends?",
    "Describe your experience with multimedia content creation.",
    "What's your process for developing creative concepts?",
    "How do you manage multiple projects with different deadlines?",
    "Tell me about a time you pushed creative boundaries.",
    "What's your experience with brand development?",
    "How do you approach audience targeting in creative work?",
    "Describe a time you had to adapt your creative style.",
    "What's your experience with social media content?",
    "How do you handle criticism of your creative work?",
    "Tell me about your approach to storytelling."
  ],

  Engineering: [
    "Tell me about yourself and your engineering background.",
    "Walk me through a complex engineering project you led.",
    "How do you approach problem-solving in engineering?",
    "Describe your experience with CAD or design software.",
    "What's your process for ensuring safety and compliance?",
    "How do you stay updated with engineering standards and regulations?",
    "Tell me about a time you had to optimize a design or process.",
    "What's your experience with project management in engineering?",
    "How do you handle technical challenges or setbacks?",
    "Describe a time you had to work within budget constraints.",
    "What's your approach to testing and validation?",
    "How do you collaborate with other engineering disciplines?",
    "Tell me about your experience with manufacturing processes.",
    "What's your approach to documentation and specifications?",
    "How do you balance innovation with practical constraints?",
    "Describe a time you improved an existing system or design.",
    "What's your experience with quality control?",
    "How do you communicate technical information to non-engineers?",
    "Tell me about a project where you had to meet strict deadlines.",
    "What's your approach to sustainability in engineering?",
    "How do you manage risks in engineering projects?",
    "Describe your experience with prototyping and iteration.",
    "What tools and methodologies do you use in your work?",
    "How do you ensure your designs are cost-effective?",
    "Tell me about the most challenging engineering problem you've solved."
  ],

  Cybersecurity: [
    "Tell me about yourself and your cybersecurity background.",
    "Walk me through how you would respond to a security breach.",
    "What frameworks and standards do you use in security? (NIST, ISO 27001, etc.)",
    "Describe a time you identified and mitigated a critical security vulnerability.",
    "How do you stay current with emerging threats and attack vectors?",
    "What's your approach to conducting a penetration test?",
    "Tell me about your experience with SIEM tools and log analysis.",
    "How do you prioritize security vulnerabilities for remediation?",
    "Describe your experience with incident response and forensics.",
    "What's your approach to threat hunting?",
    "How do you balance security requirements with business needs?",
    "Tell me about a time you had to explain a security risk to non-technical stakeholders.",
    "What's your experience with cloud security? (AWS, Azure, GCP)",
    "How do you approach application security testing?",
    "Describe your experience with security automation and orchestration.",
    "What's your process for conducting security risk assessments?",
    "How do you handle zero-day vulnerabilities?",
    "Tell me about your experience with network security and firewalls.",
    "What's your approach to identity and access management?",
    "How do you test and validate security controls?",
    "Describe a time you implemented a security solution that improved the organization's posture.",
    "What's your experience with compliance frameworks? (SOC 2, PCI DSS, HIPAA, GDPR)",
    "How do you approach security awareness training?",
    "Tell me about a time you had to work under pressure during a security incident.",
    "What tools do you use for vulnerability scanning and management?",
    "How do you perform malware analysis?",
    "Describe your experience with red team or blue team operations.",
    "What's your approach to securing CI/CD pipelines?",
    "How do you handle insider threats?",
    "Tell me about the most challenging security incident you've responded to."
  ],

  Hospitality: [
    "Tell me about yourself and your experience in hospitality.",
    "How do you handle difficult or unhappy guests?",
    "Describe a time you went above and beyond for a customer.",
    "What's your approach to managing multiple events or bookings simultaneously?",
    "How do you stay organized when coordinating complex travel arrangements?",
    "Tell me about a time you had to resolve a last-minute crisis.",
    "How do you build relationships with vendors and partners?",
    "What destination expertise do you bring to this role?",
    "How do you ensure exceptional guest experiences?",
    "Describe your experience with event budgeting and cost management.",
    "How do you handle cultural sensitivities when planning international travel?",
    "Tell me about a successful event you've coordinated from start to finish.",
    "What booking systems and travel technology are you familiar with?",
    "How do you stay updated on travel trends and new destinations?",
    "Describe a time you had to manage competing client priorities.",
    "How do you measure success in hospitality and events?",
    "Tell me about your negotiation experience with hotels and venues.",
    "How do you create personalized experiences for different types of travelers?",
    "What's your approach to risk management in event planning?",
    "How do you handle feedback and complaints professionally?"
  ],

  "Public Sector": [
    "Tell me about your experience working in public service or non-profit organizations.",
    "How do you develop effective workforce training programs?",
    "Describe your grant writing experience and success rate.",
    "What's your approach to community engagement and stakeholder management?",
    "How do you measure program impact and effectiveness?",
    "Tell me about a time you had to navigate government regulations and compliance.",
    "How do you manage budgets in resource-constrained environments?",
    "Describe your experience with public policy development.",
    "How do you build partnerships with employers and community organizations?",
    "What research methods do you use for policy analysis?",
    "Tell me about a challenging grant proposal you've written.",
    "How do you ensure equitable access to your programs and services?",
    "Describe your experience with urban planning or community development.",
    "How do you balance competing stakeholder interests?",
    "What's your approach to volunteer management and coordination?",
    "How do you communicate complex policy issues to diverse audiences?",
    "Tell me about a successful program you developed and implemented.",
    "How do you stay informed about funding opportunities?",
    "Describe your experience with data-driven decision making in public programs.",
    "What motivates you to work in public service?"
  ],

  Sustainability: [
    "Tell me about your passion for sustainability and environmental work.",
    "How do you measure and track carbon emissions?",
    "Describe your experience with ESG (Environmental, Social, Governance) frameworks.",
    "What sustainability certifications are you familiar with? (LEED, B Corp, etc.)",
    "How do you communicate the business case for sustainability initiatives?",
    "Tell me about a successful sustainability program you've implemented.",
    "How do you stay updated on climate science and environmental regulations?",
    "Describe your experience with renewable energy projects.",
    "How do you engage stakeholders in sustainability efforts?",
    "What metrics do you use to measure sustainability performance?",
    "Tell me about a time you had to overcome resistance to green initiatives.",
    "How do you conduct life cycle assessments?",
    "Describe your experience with sustainability reporting standards (GRI, CDP, etc.).",
    "How do you balance environmental goals with business objectives?",
    "What's your approach to circular economy principles?",
    "Tell me about your experience with climate risk assessment.",
    "How do you calculate scope 1, 2, and 3 emissions?",
    "Describe a time you identified cost savings through sustainability measures.",
    "What renewable energy technologies are you most familiar with?",
    "How do you promote sustainable behavior change in organizations?"
  ],

  "Real Estate": [
    "Tell me about your real estate experience and specialization.",
    "How do you evaluate property investment opportunities?",
    "Describe your approach to property valuation and market analysis.",
    "What's your experience with commercial vs. residential real estate?",
    "How do you build and maintain relationships with property owners?",
    "Tell me about a complex negotiation you've handled.",
    "How do you conduct due diligence on property acquisitions?",
    "Describe your experience with property management.",
    "What market research tools and databases do you use?",
    "How do you assess location and development potential?",
    "Tell me about a challenging deal you closed.",
    "How do you stay informed about real estate market trends?",
    "Describe your experience with financing and capital raising.",
    "What's your approach to tenant relations and retention?",
    "How do you manage property maintenance and operations?",
    "Tell me about your experience with zoning and land use regulations.",
    "How do you create financial models for real estate investments?",
    "Describe a time you identified an undervalued property opportunity.",
    "What property management software are you familiar with?",
    "How do you handle property disputes or difficult situations?"
  ]
};

// General questions that apply to all roles
export const generalQuestions: string[] = [
  "Tell me about yourself.",
  "Why are you interested in this position?",
  "What are your greatest strengths?",
  "What are your areas for improvement?",
  "Where do you see yourself in 5 years?",
  "Why do you want to work for our company?",
  "Tell me about a time you failed and what you learned.",
  "How do you handle stress and pressure?",
  "What motivates you?",
  "Do you have any questions for me?"
];

export function getQuestionsForRole(category: string): string[] {
  const categoryQuestions = questionsByCategory[category] || questionsByCategory['Technology'];
  const allQuestions = [...generalQuestions, ...categoryQuestions];

  // Shuffle and return 20 questions
  return allQuestions.sort(() => Math.random() - 0.5).slice(0, 20);
}
